#!/usr/bin/env python3
"""Pack TTF files into the binary format consumed by esp_mmap_assets."""

from __future__ import annotations

import argparse
import struct
from pathlib import Path


MAGIC = b"MMAP"
FORMAT_VERSION = 0x00010000
ASSET_PREFIX = b"\x5a\x5a"


def enum_name(partition: str, filename: str) -> str:
    normalized = "".join(character if character.isalnum() else "_" for character in filename)
    return f"MMAP_{partition.upper()}_{normalized.upper()}"


def pack(input_dir: Path, partition: str) -> tuple[bytes, str]:
    font_paths = sorted(input_dir.glob("*.ttf"), key=lambda path: (path.suffix, path.stem))
    if not font_paths:
        raise RuntimeError(f"no .ttf files found in {input_dir}")

    max_name_length = (max(len(path.name.encode("utf-8")) for path in font_paths) + 4) & ~3
    table = bytearray()
    payload = bytearray()
    header_entries: list[tuple[str, int]] = []

    for index, path in enumerate(font_paths):
        name = path.name.encode("utf-8")
        if len(name) >= max_name_length:
            raise RuntimeError(f"asset name is too long: {path.name}")

        font_data = path.read_bytes()
        offset = len(payload)
        table.extend(name.ljust(max_name_length, b"\0"))
        table.extend(struct.pack("<IIHH", len(font_data), offset, 0, 0))
        payload.extend(ASSET_PREFIX)
        payload.extend(font_data)
        header_entries.append((path.name, index))

    body = bytes(table + payload)
    checksum = sum(body) & 0xFFFF
    binary_header = struct.pack(
        "<4sIIIII8s",
        MAGIC,
        FORMAT_VERSION,
        max_name_length,
        len(font_paths),
        checksum,
        len(body),
        b"\0" * 8,
    )

    macro_prefix = f"MMAP_{partition.upper()}"
    header_lines = [
        "/* Generated by tools/pack_font_assets.py. Do not edit. */",
        "#pragma once",
        "",
        f"#define {macro_prefix}_FILES {len(font_paths)}",
        f"#define {macro_prefix}_CHECKSUM 0x{checksum:04X}",
        "",
        f"enum {macro_prefix}_LISTS {{",
    ]
    for filename, index in header_entries:
        header_lines.append(f"    {enum_name(partition, filename)} = {index}, /* {filename} */")
    header_lines.extend(["};", ""])
    return binary_header + body, "\n".join(header_lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-dir", type=Path, required=True)
    parser.add_argument("--output-bin", type=Path, required=True)
    parser.add_argument("--output-header", type=Path, required=True)
    parser.add_argument("--partition", required=True)
    parser.add_argument("--max-size", type=lambda value: int(value, 0), required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    binary, header = pack(args.input_dir, args.partition)
    if len(binary) > args.max_size:
        raise RuntimeError(
            f"font assets use {len(binary)} bytes, exceeding partition size {args.max_size}"
        )

    args.output_bin.parent.mkdir(parents=True, exist_ok=True)
    args.output_header.parent.mkdir(parents=True, exist_ok=True)
    args.output_bin.write_bytes(binary)
    args.output_header.write_text(header, encoding="utf-8")
    free = args.max_size - len(binary)
    print(
        f"Packed {args.input_dir}: {len(binary)} bytes used, "
        f"{free} bytes free in {args.partition}"
    )


if __name__ == "__main__":
    main()
